In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
data = pd.read_csv('hate crime.csv')

In [5]:
data.head()

state  median_household_income  share_unemployed_seasonal  \
0     Alabama                    42278                      0.060   
1      Alaska                    67629                      0.064   
2     Arizona                    49254                      0.063   
3    Arkansas                    44922                      0.052   
4  California                    60487                      0.059   

   share_population_in_metro_areas  share_population_with_high_school_degree  \
0                             0.64                                     0.821   
1                             0.63                                     0.914   
2                             0.90                                     0.842   
3                             0.69                                     0.824   
4                             0.97                                     0.806   

   share_non_citizen  share_white_poverty  gini_index  share_non_white  \
0               0.02                 0.12       0.472             0.35   
1               0.04                 0.06       0.422             0.42   
2               0.10                 0.09       0.455             0.49   
3               0.04                 0.12       0.458             0.26   
4               0.13                 0.09       0.471             0.61   

   share_voters_voted_trump  hate_crimes_per_100k_splc  \
0                      0.63                   0.125839   
1                      0.53                   0.143740   
2                      0.50                   0.225320   
3                      0.60                   0.069061   
4                      0.33                   0.255805   

   avg_hatecrimes_per_100k_fbi  
0                     1.806410  
1                     1.656700  
2                     3.413928  
3                     0.869209  
4                     2.397986

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 12 columns):
 #   Column                                    Non-Null Count  Dtype  
---  ------                                    --------------  -----  
 0   state                                     51 non-null     object 
 1   median_household_income                   51 non-null     int64  
 2   share_unemployed_seasonal                 51 non-null     float64
 3   share_population_in_metro_areas           51 non-null     float64
 4   share_population_with_high_school_degree  51 non-null     float64
 5   share_non_citizen                         48 non-null     float64
 6   share_white_poverty                       51 non-null     float64
 7   gini_index                                51 non-null     float64
 8   share_non_white                           51 non-null     float64
 9   share_voters_voted_trump                  51 non-null     float64
 10  hate_crimes_per_100k_splc               

In [7]:
data.dropna(inplace=True)

In [9]:
predictor = data['median_household_income']
target = data['avg_hatecrimes_per_100k_fbi']
X = predictor.values
y = target.values
#X = data.iloc[:,1].values
#y = data.iloc[,:11].values

In [16]:
X = X[:, np.newaxis]

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 42)

In [20]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [21]:
reg_model = linear_model.LinearRegression()

In [22]:
reg_model.fit(X_train, y_train)

LinearRegression()

In [23]:
y_pred = reg_model.predict(X_test)

In [24]:
y_pred

array([2.56723729, 2.08772804, 2.92271595, 1.72128045, 2.398621  ,
       2.66563822, 2.4644346 , 2.2666743 , 2.74096533])

In [26]:
MSE = mean_squared_error(y_test, y_pred)
MSE

7.986280836255665

In [27]:
RMSE = np.sqrt(MSE)
RMSE

2.826000855671432

In [28]:
reg_model.coef_

array([3.54981681e-05])

In [29]:
reg_model.intercept_

0.31725690777768945

In [30]:
R2 = r2_score(y_test, y_pred)
R2

0.039228844547419706

In [31]:
X_new = np.array([[84738]])

In [32]:
reg_model.predict(X_new)

array([3.32530067])

Multiple Linear Regression

In [33]:
multi_X = data.iloc[:,[1,2,4,5,6,8,9]].values
multi_y = data.iloc[:,11].values

In [34]:
multi_X_train, multi_X_test, multi_y_train, multi_y_test = train_test_split(multi_X, multi_y, test_size = 0.2, random_state = 42)

In [35]:
multi_reg_model = linear_model.LinearRegression()

In [36]:
multi_reg_model.fit(multi_X_train, multi_y_train)

LinearRegression()

In [37]:
multi_y_pred = multi_reg_model.predict(multi_X_test)

In [38]:
multi_y_pred

array([2.17717086, 3.191053  , 2.86699638, 4.49569385, 4.04467552,
       1.63512176, 2.95217362, 2.70718665, 2.82466099])

In [39]:
multi_MSE = mean_squared_error(multi_y_test, multi_y_pred)
multi_MSE

9.401680013742052

In [40]:
multi_reg_model.coef_

array([ 1.34467940e-05,  6.55407051e+01, -4.70790854e+00,  3.30717191e+01,
       -2.37482012e+00, -1.01184270e+01, -1.01547302e+00])

In [41]:
multi_reg_model.intercept_

4.488246944759546

In [42]:
multi_RMSE = np.sqrt(multi_MSE)
multi_RMSE

3.066215911142275

In [43]:
multi_R2 = r2_score(multi_y_test, multi_y_pred)
multi_R2

-0.1310474994807973