In [1]:
import numpy as np

In [2]:
array_1 = np.array([1,2,3,4,5])
array_2 = np.array(['a','b','c','d','e'])

In [3]:
print(array_1)
print(array_2)

[1 2 3 4 5]
['a' 'b' 'c' 'd' 'e']


In [4]:
type(array_1)

numpy.ndarray

In [5]:
type(array_2)

numpy.ndarray

In [6]:
array_1.shape  #(columns, 1 row)

(5,)

In [7]:
array_2.shape

(5,)

In [8]:
array_3 = np.array([[1,5,9],
                   [2,6,0]])

In [9]:
array_3

array([[1, 5, 9],
       [2, 6, 0]])

In [10]:
array_example = np.array([[1,5,9],
                         [2,6,np.NaN]]) # NaN for missing data

In [11]:
array_example

array([[ 1.,  5.,  9.],
       [ 2.,  6., nan]])

In [12]:
array_3.shape  #(rows, columns)

(2, 3)

In [13]:
len(array_1)

5

In [14]:
len(array_3)  #number of rows is the length

2

In [15]:
array_1 ** 3

array([  1,   8,  27,  64, 125], dtype=int32)

In [16]:
array_3 ** 3

array([[  1, 125, 729],
       [  8, 216,   0]], dtype=int32)

In [17]:
array_1.sum()

15

In [18]:
sum(array_1)  #same as above if only one row

15

In [19]:
array_3.sum()

23

In [20]:
sum(array_3)  #different from above

array([ 3, 11,  9])

In [21]:
array_1.std()

1.4142135623730951

In [22]:
array_3.std()

3.131382371342656

In [23]:
array_4 = np.arange(10, -5, -0.5)  #to create an array from 10 to -5(not included) with -0.5 intervals

In [24]:
array_4

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. , -0.5,
       -1. , -1.5, -2. , -2.5, -3. , -3.5, -4. , -4.5])

In [25]:
array_5 = np.arange(20)  #to create an array from 0 to 20(not included) with 1 intervals

In [26]:
array_5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])