In [1]:
import numpy as np

In [2]:
array_1 = np.array([2, 16 ,4, 75, 48, 8])

In [3]:
array_1[0]

2

In [4]:
array_1[3:5]

array([75, 48])

In [5]:
array_1[[1,3,5]]  #important: double square brackets

array([16, 75,  8])

In [6]:
array_2 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [7]:
array_2[1][2]  #1→[4,5,6], 2→6

6

In [8]:
array_2[1,2]  #same as above

6

In [9]:
array_2[[1,2]]  #double [] take the array location as a whole

array([[4, 5, 6],
       [7, 8, 9]])

In [10]:
array_2[0:2,1:3]  #first slice includes [1,2,3]&[4,5,6], second slice locates to [2,3]&[5,6]

array([[2, 3],
       [5, 6]])

In [11]:
array_slices = np.array([array_2[0][0:2],
                    array_2[2][1:3]])  #to slice and get array [1,2],[8,9]

In [12]:
array_slices

array([[1, 2],
       [8, 9]])

In [13]:
array_1[[True, True, True,False, False, True]]

array([ 2, 16,  4,  8])

In [14]:
array_1 > 10

array([False,  True, False,  True,  True, False])

In [15]:
array_1[[False,  True, False,  True,  True, False]]

array([16, 75, 48])

In [16]:
array_1[array_1>10]

array([16, 75, 48])

In [17]:
array_1[(array_1>10) & (array_1 !=75)]

array([16, 48])

In [18]:
array_1[(array_1>10) | (array_1 == 2)]

array([ 2, 16, 75, 48])

In [19]:
array_3 = np.array([3,5,7,9])
array_4 = np.array([4,5,7,1])

In [20]:
array_3[array_3 == array_4]  #number order in the array matters

array([5, 7])

In [21]:
array_3[array_3 != array_4]

array([3, 9])

In [22]:
array_4[array_3 != array_4]

array([4, 1])